// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using daviagens_api.Context;

#nullable disable

namespace daviagens_api.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("daviagens_api.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("dataNasc")
                        .HasColumnType("longtext");

                    b.Property<string>("nome")
                        .HasColumnType("longtext");

                    b.Property<string>("numPassaporte")
                        .HasColumnType("longtext");

                    b.Property<string>("telefone")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            dataNasc = "1996-12-25",
                            nome = "Monkey D. Luffy",
                            numPassaporte = "BR000001",
                            telefone = "(11)1234-5678"
                        },
                        new
                        {
                            Id = 2,
                            dataNasc = "1990-04-01",
                            nome = "Naruto Uzumaki",
                            numPassaporte = "BR000002",
                            telefone = "(11)1234-5678"
                        },
                        new
                        {
                            Id = 3,
                            dataNasc = "1998-10-21",
                            nome = "Tajiro Kamada",
                            numPassaporte = "BR000003",
                            telefone = "(11)1234-5678"
                        },
                        new
                        {
                            Id = 4,
                            dataNasc = "1987-01-31",
                            nome = "Yusuke Urameshi",
                            numPassaporte = "BR000004",
                            telefone = "(11)1234-5678"
                        },
                        new
                        {
                            Id = 5,
                            dataNasc = "1996-11-24",
                            nome = "Kagome Higurashi",
                            numPassaporte = "BR000005",
                            telefone = "(11)1234-5678"
                        });
                });

            modelBuilder.Entity("daviagens_api.Models.Contato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .HasColumnType("longtext");

                    b.Property<string>("mensagem")
                        .HasColumnType("longtext");

                    b.Property<string>("nome")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Contatos");
                });

            modelBuilder.Entity("daviagens_api.Models.Destino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<float>("desconto")
                        .HasColumnType("float");

                    b.Property<string>("descricao")
                        .HasColumnType("longtext");

                    b.Property<string>("descricaoCompleta")
                        .HasColumnType("longtext");

                    b.Property<string>("img")
                        .HasColumnType("longtext");

                    b.Property<string>("nome")
                        .HasColumnType("longtext");

                    b.Property<string>("tipo")
                        .HasColumnType("longtext");

                    b.Property<float>("valor")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Destinos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            desconto = 7f,
                            descricao = "Rio de Janeiro, beleza que inspira.",
                            descricaoCompleta = "O Rio de Janeiro, cidade maravilhosa do Brasil, encanta com suas praias deslumbrantes, montanhas majestosas, e um carnaval contagiante, proporcionando uma experiência única e apaixonante aos visitantes.",
                            img = "https://raw.githubusercontent.com/RabbitDeWitt/Atividade-Modulo-2/master/site/assets/imgs/urca.jpg",
                            nome = "Rio de Janeiro",
                            tipo = "NACIONAL",
                            valor = 705f
                        },
                        new
                        {
                            Id = 2,
                            desconto = 20f,
                            descricao = "Seoul, a cidade das mil faces e infinitas possibilidades.",
                            descricaoCompleta = "Seoul, uma metrópole eletrizante que combina tradição e modernidade, oferecendo uma rica tapeçaria cultural, tecnológica e gastronômica, que hipnotiza e encanta seus visitantes.",
                            img = "https://raw.githubusercontent.com/RabbitDeWitt/Atividade-Modulo-2/master/site/assets/imgs/seoul.jpg",
                            nome = "Seoul",
                            tipo = "INTERNACIONAL",
                            valor = 10675f
                        },
                        new
                        {
                            Id = 3,
                            desconto = 7f,
                            descricao = "Salvador, onde história e encanto se encontram.",
                            descricaoCompleta = "Salvador, a cidade do axé e da cultura afro-brasileira, encanta com suas praias deslumbrantes, arquitetura colonial colorida e festas animadas, emanando uma energia contagiante em cada esquina.",
                            img = "https://raw.githubusercontent.com/RabbitDeWitt/Atividade-Modulo-2/master/site/assets/imgs/salvador.jpg",
                            nome = "Salvador",
                            tipo = "NACIONAL",
                            valor = 866f
                        },
                        new
                        {
                            Id = 4,
                            desconto = 15f,
                            descricao = "São Francisco, cidade da Califórnia encantadora.",
                            descricaoCompleta = "São Francisco, cidade vibrante na costa oeste dos EUA, é famosa pela icônica Golden Gate Bridge, cenário tecnológico e cultura diversificada, proporcionando uma experiência cativante e inesquecível aos seus visitantes.",
                            img = "https://raw.githubusercontent.com/RabbitDeWitt/Atividade-Modulo-2/master/site/assets/imgs/sanfrancisco.jpg",
                            nome = "São Francisco",
                            tipo = "INTERNACIONAL",
                            valor = 4180f
                        },
                        new
                        {
                            Id = 5,
                            desconto = 20f,
                            descricao = "Sydney, a deslumbrante cidade australiana.",
                            descricaoCompleta = "Sydney, a espetacular metrópole australiana, que combina praias de tirar o fôlego, uma arquitetura moderna e icônica, além de uma vida cultural vibrante, tornando-se uma das cidades mais fascinantes e desejadas do mundo.",
                            img = "https://raw.githubusercontent.com/RabbitDeWitt/Atividade-Modulo-2/master/site/assets/imgs/sidney.jpg",
                            nome = "Sidney",
                            tipo = "INTERNACIONAL",
                            valor = 9275f
                        },
                        new
                        {
                            Id = 6,
                            desconto = 5f,
                            descricao = "Mariana, uma encantadora cidade mineira.",
                            descricaoCompleta = "Mariana, cidade histórica de Minas Gerais, fascina com suas igrejas barrocas preservadas, casarões coloniais e paisagens pitorescas, transportando os visitantes para um passado encantador do Brasil colonial.",
                            img = "https://raw.githubusercontent.com/RabbitDeWitt/Atividade-Modulo-2/master/site/assets/imgs/mariana.jpg",
                            nome = "Mariana",
                            tipo = "NACIONAL",
                            valor = 874f
                        },
                        new
                        {
                            Id = 7,
                            desconto = 5f,
                            descricao = "Curitiba, verdejante metrópole com rica cultura brasileira.",
                            descricaoCompleta = "Curitiba, a capital ecológica do Brasil, encanta com seus parques bem-cuidados, sistema de transporte eficiente e uma rica cena cultural, oferecendo uma qualidade de vida invejável aos seus moradores.",
                            img = "https://raw.githubusercontent.com/RabbitDeWitt/Atividade-Modulo-2/master/site/assets/imgs/curitiba.jpg",
                            nome = "Curitiba",
                            tipo = "NACIONAL",
                            valor = 483f
                        },
                        new
                        {
                            Id = 8,
                            desconto = 10f,
                            descricao = "Recife, cidade encantadora do Nordeste brasileiro.",
                            descricaoCompleta = "Recife, a joia do Nordeste brasileiro, encanta com suas praias de águas mornas e coqueirais, sua rica história que mescla tradição e modernidade, e a alegria contagiante de seu povo, sempre acolhedor e vibrante.",
                            img = "https://raw.githubusercontent.com/RabbitDeWitt/Atividade-Modulo-2/master/site/assets/imgs/recife.jpg",
                            nome = "Recife",
                            tipo = "NACIONAL",
                            valor = 1596f
                        },
                        new
                        {
                            Id = 9,
                            desconto = 13f,
                            descricao = "Paris, a cidade luz do romantismo e da cultura.",
                            descricaoCompleta = "Paris, a romântica Cidade Luz, cativa com seus ícones icônicos como a Torre Eiffel e o Louvre, além de uma cultura sofisticada e gastronomia refinada, tornando-se um Destinos inesquecível para os apaixonados por arte, história e charme.",
                            img = "https://raw.githubusercontent.com/RabbitDeWitt/Atividade-Modulo-2/master/site/assets/imgs/paris.jpg",
                            nome = "Paris",
                            tipo = "INTERNACIONAL",
                            valor = 4716f
                        },
                        new
                        {
                            Id = 10,
                            desconto = 10f,
                            descricao = "Londres, a metrópole multicultural e cheia de história.",
                            descricaoCompleta = "Londres, a capital britânica, brilha com uma rica tapeçaria de história e modernidade, destacando-se com seus marcos emblemáticos, cultura diversificada e dinâmica cena artística, tornando-se uma cidade perfeita para explorar.",
                            img = "https://raw.githubusercontent.com/RabbitDeWitt/Atividade-Modulo-2/master/site/assets/imgs/london.jpg",
                            nome = "Londres",
                            tipo = "INTERNACIONAL",
                            valor = 5347f
                        },
                        new
                        {
                            Id = 11,
                            desconto = 15f,
                            descricao = "Tóquio, metrópole futurista e vibrante do Japão.",
                            descricaoCompleta = "Tóquio, combina modernidade e tradição em uma harmoniosa fusão. Seus arranha-céus reluzentes, templos ancestrais e cultura pop enérgica encantam os visitantes do mundo todo, oferecendo uma experiência única e inesquecível.",
                            img = "https://raw.githubusercontent.com/RabbitDeWitt/Atividade-Modulo-2/master/site/assets/imgs/tokyo.jpg",
                            nome = "Tóquio",
                            tipo = "INTERNACIONAL",
                            valor = 7547f
                        },
                        new
                        {
                            Id = 12,
                            desconto = 10f,
                            descricao = "São Luís, cidade histórica e culturalmente rica.",
                            descricaoCompleta = "São Luís, capital do Maranhão, é um tesouro histórico com sua arquitetura colonial preservada e rica herança cultural. Suas praias exuberantes e gastronomia típica completam a experiência encantadora.",
                            img = "https://raw.githubusercontent.com/RabbitDeWitt/Atividade-Modulo-2/master/site/assets/imgs/maranhao.jpg",
                            nome = "Maranhão",
                            tipo = "NACIONAL",
                            valor = 1856f
                        });
                });

            modelBuilder.Entity("daviagens_api.Models.Pacote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .HasColumnType("longtext");

                    b.Property<float>("valor")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Pacotes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            nome = "Economica",
                            valor = 0f
                        },
                        new
                        {
                            Id = 2,
                            nome = "Economica Premium",
                            valor = 400f
                        },
                        new
                        {
                            Id = 3,
                            nome = "Executiva",
                            valor = 1500f
                        },
                        new
                        {
                            Id = 4,
                            nome = "Primeira Classe",
                            valor = 5000f
                        });
                });

            modelBuilder.Entity("daviagens_api.Models.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("clienteId")
                        .HasColumnType("int");

                    b.Property<string>("dataPartida")
                        .HasColumnType("longtext");

                    b.Property<string>("dataRetorno")
                        .HasColumnType("longtext");

                    b.Property<int>("destinoId")
                        .HasColumnType("int");

                    b.Property<int>("pacoteId")
                        .HasColumnType("int");

                    b.Property<float>("valor")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("clienteId");

                    b.HasIndex("destinoId");

                    b.HasIndex("pacoteId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("daviagens_api.Models.Reserva", b =>
                {
                    b.HasOne("daviagens_api.Models.Cliente", "cliente")
                        .WithMany("reservas")
                        .HasForeignKey("clienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("daviagens_api.Models.Destino", "destino")
                        .WithMany("reservas")
                        .HasForeignKey("destinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("daviagens_api.Models.Pacote", "pacote")
                        .WithMany("reservas")
                        .HasForeignKey("pacoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cliente");

                    b.Navigation("destino");

                    b.Navigation("pacote");
                });

            modelBuilder.Entity("daviagens_api.Models.Cliente", b =>
                {
                    b.Navigation("reservas");
                });

            modelBuilder.Entity("daviagens_api.Models.Destino", b =>
                {
                    b.Navigation("reservas");
                });

            modelBuilder.Entity("daviagens_api.Models.Pacote", b =>
                {
                    b.Navigation("reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
